### ISSUE TITLE
Nicht Nextcloud....

### ISSUE THREAD

**Issue by JonasMayerDev** [JanisJ4/Raspi-Cloud#1]
Bitte migriere zu Nextcloud ;)

**Comment by JanisJ4** [comment]
Hallo,

ich schätze Ihr Interesse und Ihre Empfehlung. Allerdings habe ich umfangreiche Tests und Vergleiche zwischen meiner selbst entwickelten Cloud-Lösung und Nextcloud durchgeführt. Diese Tests konzentrierten sich auf wichtige Aspekte wie Geschwindigkeit, Reaktionszeit und Effizienz, insbesondere in Umgebungen mit begrenzter Rechenleistung und langsamer Internetverbindung – Bedingungen, die oft in abgelegenen oder weniger entwickelten Regionen vorkommen.

Die Ergebnisse dieser Tests zeigen, dass meine Cloud-Lösung in mehreren Schlüsselbereichen überlegen ist:

- Geschwindigkeit: Sowohl beim Upload als auch beim Download von Dateien verschiedener Größen war meine Lösung deutlich schneller als Nextcloud.
- Reaktionszeit: Die Wartezeit bis zur ersten Antwort des Servers war bei meiner Cloud erheblich kürzer, was eine schnellere Interaktion ermöglicht.
- Effizienz: Die CPU-Auslastung während des Betriebs war bei meiner Cloud geringer, was besonders auf Hardware mit eingeschränkten Ressourcen wie dem Raspberry Pi wichtig ist.

Diese Vorteile sind entscheidend, um eine zugängliche, zuverlässige und effiziente Cloud-Storage-Lösung für alle Nutzer zu bieten, unabhängig von ihrer Internetgeschwindigkeit oder Hardware. Während Nextcloud zweifellos eine starke und beliebte Wahl für viele Anwendungsfälle ist, bietet meine Cloud eine Lösung für die in der Realität oft anzutreffenden eingeschränkten Möglichkeiten.

Da ich bestrebt bin, auch für all diese Menschen eine gute Cloud-Lösung zu schaffen, werde ich bei meiner aktuellen Implementierung bleiben und auch weiter an ihr entwickeln. Ich bin offen für weitere Vorschläge und Diskussionen über mögliche Verbesserungen und danke Ihnen für das Interesse an meinem Projekt.

Mit freundlichen Grüßen
